import type {Card,Progress} from './types';

type ProgressMap=Record<string,Progress|undefined>;
type VaultFile={name:string;data:Uint8Array};
const encoder=new TextEncoder();
const ROOM_NAMES=['理论与改革','经济与发展','科教与创新','乡村与生态','民生与法治','文化与党建','开放与安全','多彩贵州'];
function safeFileStem(value:string){const cleaned=value.replace(/[\\/:*?"<>|\u0000-\u001f]/g,'－').replace(/[.\s]+$/g,'').trim();return (cleaned||'未命名知识点').slice(0,120)}
function yamlString(value:string){return JSON.stringify(value)}
function tagName(value:string){return value.trim().replace(/^#+/,'').replace(/[\s\\]+/g,'-').replace(/[\[\]|^]/g,'').replace(/-+/g,'-')}
function fileStemMap(cards:Card[]){const used=new Map<string,number>(),result=new Map<string,string>();for(const card of cards){const base=safeFileStem(card.title),key=base.toLocaleLowerCase(),index=(used.get(key)||0)+1;used.set(key,index);result.set(card.id,index===1?base:`${base}（${index}）`)}return result}
function relationMap(cards:Card[]){const known=new Set(cards.map(card=>card.id));const result=new Map<string,Map<string,string>>(cards.map(card=>[card.id,new Map()]));for(const card of cards)for(const relation of card.links){if(!known.has(relation.id)||relation.id===card.id)continue;result.get(card.id)!.set(relation.id,relation.label||'关联');if(!result.get(relation.id)!.has(card.id))result.get(relation.id)!.set(card.id,relation.label||'关联')}return result}
function noteText(card:Card,cardsById:Map<string,Card>,stems:Map<string,string>,relations:Map<string,Map<string,string>>,progress:ProgressMap){const roomName=ROOM_NAMES[card.room]||'其他';const tags=[...new Set(['知政',`主题/${roomName}`,`范围/${card.scope}`,...card.keywords].map(tagName).filter(Boolean))];const aliases=[...new Set(card.aliases.filter(alias=>alias&&alias!==card.title))];const related=[...(relations.get(card.id)||new Map()).entries()].map(([id,label])=>{const target=cardsById.get(id);if(!target)return '';return `- [[${stems.get(id)}|${target.title}]] — ${label}`}).filter(Boolean);const original=(card.original?.length?card.original:card.points).join('\n\n');const personalNote=progress[card.id]?.note?.trim()||'';return ['---',`id: ${yamlString(card.id)}`,`title: ${yamlString(card.title)}`,'aliases:',...(aliases.length?aliases.map(alias=>`  - ${yamlString(alias)}`):['  - '+yamlString(card.title)]),'tags:',...tags.map(tag=>`  - ${yamlString(tag)}`),`date: ${yamlString(card.date)}`,`scope: ${yamlString(card.scope)}`,`theme: ${yamlString(roomName)}`,`source: ${yamlString(card.source.url)}`,'---','',`# ${card.title}`,'','## 原文','',original,'','## 个人笔记','',personalNote,'','## 关联知识点','',...(related.length?related:['（暂无关联）']),'','## 资料链接','',`- [${card.source.title}](${card.source.url})`,'' ].join('\n')}
function crc32(bytes:Uint8Array){let crc=0xffffffff;for(const byte of bytes){crc^=byte;for(let bit=0;bit<8;bit++)crc=(crc>>>1)^((crc&1)?0xedb88320:0)}return (crc^0xffffffff)>>>0}
function dosDateTime(date:Date){const year=Math.max(1980,date.getFullYear());return {date:((year-1980)<<9)|((date.getMonth()+1)<<5)|date.getDate(),time:(date.getHours()<<11)|(date.getMinutes()<<5)|(date.getSeconds()>>1)}}
function concat(parts:Uint8Array[]){const length=parts.reduce((sum,part)=>sum+part.length,0),out=new Uint8Array(length);let offset=0;for(const part of parts){out.set(part,offset);offset+=part.length}return out}
function zip(files:VaultFile[]){const localParts:Uint8Array[]=[],centralParts:Uint8Array[]=[];let offset=0;const stamp=dosDateTime(new Date());for(const file of files){const name=encoder.encode(file.name),crc=crc32(file.data);const local=new Uint8Array(30+name.length),lv=new DataView(local.buffer);lv.setUint32(0,0x04034b50,true);lv.setUint16(4,20,true);lv.setUint16(6,0x0800,true);lv.setUint16(8,0,true);lv.setUint16(10,stamp.time,true);lv.setUint16(12,stamp.date,true);lv.setUint32(14,crc,true);lv.setUint32(18,file.data.length,true);lv.setUint32(22,file.data.length,true);lv.setUint16(26,name.length,true);local.set(name,30);localParts.push(local,file.data);const central=new Uint8Array(46+name.length),cv=new DataView(central.buffer);cv.setUint32(0,0x02014b50,true);cv.setUint16(4,20,true);cv.setUint16(6,20,true);cv.setUint16(8,0x0800,true);cv.setUint16(10,0,true);cv.setUint16(12,stamp.time,true);cv.setUint16(14,stamp.date,true);cv.setUint32(16,crc,true);cv.setUint32(20,file.data.length,true);cv.setUint32(24,file.data.length,true);cv.setUint16(28,name.length,true);cv.setUint32(42,offset,true);central.set(name,46);centralParts.push(central);offset+=local.length+file.data.length}const central=concat(centralParts),end=new Uint8Array(22),ev=new DataView(end.buffer);ev.setUint32(0,0x06054b50,true);ev.setUint16(8,files.length,true);ev.setUint16(10,files.length,true);ev.setUint32(12,central.length,true);ev.setUint32(16,offset,true);const archive=concat([...localParts,central,end]);return new Blob([archive.buffer as ArrayBuffer],{type:'application/zip'})}
export function createObsidianVault(cards:Card[],progress:ProgressMap){const stems=fileStemMap(cards),relations=relationMap(cards),cardsById=new Map(cards.map(card=>[card.id,card]));const files=cards.map(card=>({name:`知政知识图谱/知识点/${stems.get(card.id)}.md`,data:encoder.encode(noteText(card,cardsById,stems,relations,progress))}));const relationCount=new Set(cards.flatMap(card=>card.links.filter(link=>cardsById.has(link.id)&&link.id!==card.id).map(link=>[card.id,link.id].sort().join(':')))).size;return {blob:zip(files),fileCount:files.length,relationCount}}
export function downloadObsidianVault(cards:Card[],progress:ProgressMap){const vault=createObsidianVault(cards,progress),url=URL.createObjectURL(vault.blob),a=document.createElement('a');a.href=url;a.download='知政-Obsidian知识图谱.zip';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);return vault}
