'use client';
import React,{useState,useRef,useEffect,useMemo,useCallback} from 'react';
import {LocateFixed,Network} from 'lucide-react';
import type {Card,Position} from '@/lib/types';
import {ROOMS} from '@/lib/types';
export type GraphProps={cards:Card[];all:Card[];selected:string;onSelect:(id:string)=>void;positions:Record<string,Position>;onPosition:(id:string,p:Position)=>void;local:boolean;hop:number;onLocal:(local:boolean)=>void;onHop:(n:number)=>void;};
export function neighborhood(all:Card[],id:string,depth=1){let seen=new Set([id]);for(let i=0;i<depth;i++){const next=new Set(seen);for(const c of all)for(const link of c.links)if(seen.has(c.id)||seen.has(link.id)){next.add(c.id);next.add(link.id)}seen=next;}return seen;}
export default function KnowledgeGraph({cards,all,selected,onSelect,positions,onPosition,local,hop,onLocal,onHop}:GraphProps){
 const host=useRef<HTMLDivElement>(null);const [size,setSize]=useState({w:900,h:650});const [view,setView]=useState({x:0,y:0,z:1});const viewRef=useRef(view);viewRef.current=view;
 const drag=useRef<{id?:string;sx:number;sy:number;px:number;py:number;moved:boolean}|null>(null);const touched=useRef(new Map<number,{x:number,y:number}>());const pinch=useRef<{distance:number;z:number;wx:number;wy:number}|null>(null);
 const [temp,setTemp]=useState<Record<string,Position>>({});const [hover,setHover]=useState<string|null>(null);
 const visible=useMemo(()=>local?cards.filter(c=>neighborhood(all,selected,hop).has(c.id)):cards,[cards,all,selected,local,hop]);
 const base=useMemo(()=>{
  const out:Record<string,Position>={};
  if(local){const others=visible.filter(c=>c.id!==selected);out[selected]={x:600,y:440};others.forEach((c,i)=>{const ring=others.length>10&&i>=8?1:0;const count=ring?others.length-8:Math.min(others.length,others.length>10?8:10);const n=ring?i-8:i;const a=-Math.PI/2+n/count*Math.PI*2;out[c.id]={x:600+Math.cos(a)*(ring?540:360),y:440+Math.sin(a)*(ring?420:265)};});}
  else{ROOMS.forEach((r,room)=>{all.filter(c=>c.room===room).forEach((c,i)=>{const row=Math.floor(i/3),col=i%3;out[c.id]={x:r.x+(col-1)*250+(row%2)*40,y:r.y+row*160};});});}
  return out;
 },[local,selected,visible,all]);
 const pos=useMemo(()=>Object.fromEntries(visible.map(c=>{const p=base[c.id]||{x:600,y:400};const delta=temp[c.id]||positions[c.id]||{x:0,y:0};return[c.id,{x:p.x+delta.x,y:p.y+delta.y}]})),[visible,base,positions,temp]);
 const fit=useCallback(()=>{const ps=Object.values(pos);if(!ps.length)return;const minx=Math.min(...ps.map(p=>p.x))-130,maxx=Math.max(...ps.map(p=>p.x))+130,miny=Math.min(...ps.map(p=>p.y))-75,maxy=Math.max(...ps.map(p=>p.y))+75;const z=Math.min(1.12,Math.max(.17,Math.min((size.w-80)/(maxx-minx),(size.h-150)/(maxy-miny))));setView({x:size.w/2-(minx+maxx)/2*z,y:(size.h+40)/2-(miny+maxy)/2*z,z});},[pos,size]);
 const fitRef=useRef(fit);fitRef.current=fit;
 useEffect(()=>{const el=host.current;if(!el)return;const ro=new ResizeObserver(e=>setSize({w:e[0].contentRect.width,h:e[0].contentRect.height}));ro.observe(el);return()=>ro.disconnect()},[]);
 useEffect(()=>{fitRef.current()},[selected,local,hop,cards.length,size.w,size.h]);
 const zoom=useCallback((factor:number,cx=size.w/2,cy=size.h/2)=>setView(v=>{const z=Math.min(2.5,Math.max(.15,v.z*factor));return{x:cx-(cx-v.x)*z/v.z,y:cy-(cy-v.y)*z/v.z,z}}),[size]);
 useEffect(()=>{const el=host.current;if(!el)return;const wheel=(e:WheelEvent)=>{e.preventDefault();const r=el.getBoundingClientRect();zoom(Math.exp(-e.deltaY*.0015),e.clientX-r.left,e.clientY-r.top)};el.addEventListener('wheel',wheel,{passive:false});return()=>el.removeEventListener('wheel',wheel)},[zoom]);
 const edges=useMemo(()=>{const keys=new Set(visible.map(c=>c.id));const seen=new Set<string>();return visible.flatMap(c=>c.links.filter(l=>keys.has(l.id)).flatMap(l=>{const key=[c.id,l.id].sort().join(':');if(seen.has(key))return[];seen.add(key);return[{from:c.id,to:l.id,label:l.label}]}))},[visible]);
 const active=hover||selected;const neighborIds=neighborhood(all,active,1);
 const down=(e:React.PointerEvent<HTMLDivElement>)=>{if((e.target as HTMLElement).closest('[data-controls]'))return;host.current?.setPointerCapture(e.pointerId);touched.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touched.current.size===2){const [a,b]=[...touched.current.values()];const r=host.current!.getBoundingClientRect(),cx=(a.x+b.x)/2-r.left,cy=(a.y+b.y)/2-r.top;pinch.current={distance:Math.hypot(a.x-b.x,a.y-b.y),z:view.z,wx:(cx-view.x)/view.z,wy:(cy-view.y)/view.z};drag.current=null;return;}const node=(e.target as HTMLElement).closest('[data-node]') as HTMLElement|null;const id=node?.dataset.node;const p=id?(temp[id]||positions[id]||{x:0,y:0}):view;drag.current={id,sx:e.clientX,sy:e.clientY,px:p.x,py:p.y,moved:false};};
 const move=(e:React.PointerEvent<HTMLDivElement>)=>{if(!touched.current.has(e.pointerId))return;touched.current.set(e.pointerId,{x:e.clientX,y:e.clientY});if(touched.current.size===2&&pinch.current){const [a,b]=[...touched.current.values()];const r=host.current!.getBoundingClientRect();const q=pinch.current,z=Math.min(2.5,Math.max(.15,q.z*Math.hypot(a.x-b.x,a.y-b.y)/q.distance));setView({z,x:(a.x+b.x)/2-r.left-q.wx*z,y:(a.y+b.y)/2-r.top-q.wy*z});return;}const d=drag.current;if(!d)return;const dx=e.clientX-d.sx,dy=e.clientY-d.sy;if(Math.hypot(dx,dy)>4)d.moved=true;if(d.id){const p={x:d.px+dx/viewRef.current.z,y:d.py+dy/viewRef.current.z};setTemp(t=>({...t,[d.id!]:p}));}else setView(v=>({...v,x:d.px+dx,y:d.py+dy}));};
 const up=(e:React.PointerEvent<HTMLDivElement>)=>{touched.current.delete(e.pointerId);if(pinch.current){if(touched.current.size<2)pinch.current=null;drag.current=null;return;}const d=drag.current;if(d?.id){if(d.moved)onPosition(d.id,temp[d.id]||positions[d.id]||{x:0,y:0});else onSelect(d.id);}drag.current=null;};
 return <div className="graph-canvas" ref={host} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{drag.current=null;touched.current.clear();pinch.current=null}} tabIndex={0} aria-label="知识网络。拖动画布或节点，滚轮缩放；方向键移动，加减号缩放。" onKeyDown={e=>{if(e.target!==e.currentTarget)return;const key=e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','-','='].includes(key))e.preventDefault();if(key==='+'||key==='=')zoom(1.2);if(key==='-')zoom(1/1.2);if(key.startsWith('Arrow'))setView(v=>({...v,x:v.x+(key==='ArrowLeft'?70:key==='ArrowRight'?-70:0),y:v.y+(key==='ArrowUp'?70:key==='ArrowDown'?-70:0)}));}}>
  <div className="graph-switch" data-controls><button className={!local?'active':''} onClick={()=>onLocal(false)}><Network size={15}/>全局</button><button className={local?'active':''} onClick={()=>onLocal(true)}><LocateFixed size={15}/>局部</button></div>
  <div className="graph-world" style={{transform:`translate(${view.x}px,${view.y}px) scale(${view.z})`}}>
   {!local&&ROOMS.map((r,i)=><div className="cluster-title" key={r.name} style={{left:r.x-265,top:r.y-100,color:r.color}}><span>0{i+1} / {r.place}</span><strong>{r.name}</strong></div>)}
   <svg className="edge-layer" width="5000" height="5000" viewBox="-1000 -1000 5000 5000" style={{left:-1000,top:-1000}} aria-hidden="true">{edges.map(e=>{const a=pos[e.from],b=pos[e.to];if(!a||!b)return null;const relevant=e.from===active||e.to===active;return <g key={e.from+e.to} className={relevant?'edge focused':'edge'}><path d={`M${a.x},${a.y} Q${(a.x+b.x)/2+22},${(a.y+b.y)/2-20} ${b.x},${b.y}`} stroke={relevant?ROOMS[all.find(c=>c.id===active)?.room||0].color:undefined}/>{relevant&&local&&view.z>.45&&<g transform={`translate(${(a.x+b.x)/2},${(a.y+b.y)/2-12})`}><rect x={-e.label.length*6.5-10} y={-12} width={e.label.length*13+20} height={24} rx={12}/><text textAnchor="middle" dominantBaseline="middle">{e.label}</text></g>}</g>})}</svg>
   {visible.map(c=>{const p=pos[c.id];if(!p)return null;const r=ROOMS[c.room],isSelected=c.id===selected;return <button type="button" data-node={c.id} key={c.id} className={`graph-node ${isSelected?'selected':''} ${hover&&!neighborIds.has(c.id)?'dim':''}`} style={{left:p.x,top:p.y,'--node-color':r.color} as React.CSSProperties} onPointerEnter={()=>setHover(c.id)} onPointerLeave={()=>setHover(null)} onClick={e=>{if(e.detail===0)onSelect(c.id)}} aria-label={`打开考点：${c.title}`} aria-pressed={isSelected}><span className="node-dot">{isSelected&&<Network size={23}/>}</span><span className="node-label">{c.title}</span><span className="node-meta">{c.scope==='贵州'?'贵州专属':c.kind} · {c.date.slice(0,4)}</span>{isSelected&&<span className="node-keywords">{c.must.slice(0,2).join(' / ')}</span>}</button>})}
  </div>
  {!visible.length&&<div className="graph-empty">这个筛选下没有关联考点。<button onClick={()=>onLocal(false)}>查看全部匹配知识点</button></div>}
  {local&&<div className="graph-bottom graph-depth" data-controls><div className="hop-controls"><button className={hop===1?'active':''} onClick={()=>onHop(1)}>一层关联</button><button className={hop===2?'active':''} onClick={()=>onHop(2)}>再延伸一层</button></div></div>}
 </div>;
}
